spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/myapp_db
spring.datasource.username=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.profiles.active=local